/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i chat_adaptor.h -a :chat_adaptor.cpp ..\receiver\chat.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "chat_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ReceiverAdaptor
 */

ReceiverAdaptor::ReceiverAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ReceiverAdaptor::~ReceiverAdaptor()
{
    // destructor
}

QString ReceiverAdaptor::message() const
{
    // get the value of property message
    return qvariant_cast< QString >(parent()->property("message"));
}

void ReceiverAdaptor::setMessage(const QString &value)
{
    // set the value of property message
    parent()->setProperty("message", QVariant::fromValue(value));
}

void ReceiverAdaptor::receive(const QString &encoded_image)
{
    // handle method call local.Receiver.receive
    QMetaObject::invokeMethod(parent(), "receive", Q_ARG(QString, encoded_image));
}

