/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i light_adaptor.h -a :light_adaptor.cpp ..\MyLight\light.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "light_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MyLightAdaptor
 */

MyLightAdaptor::MyLightAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MyLightAdaptor::~MyLightAdaptor()
{
    // destructor
}

bool MyLightAdaptor::isOn() const
{
    // get the value of property isOn
    return qvariant_cast< bool >(parent()->property("isOn"));
}

void MyLightAdaptor::setIsOn(bool value)
{
    // set the value of property isOn
    parent()->setProperty("isOn", QVariant::fromValue(value));
}

void MyLightAdaptor::turnOff()
{
    // handle method call local.MyLight.turnOff
    QMetaObject::invokeMethod(parent(), "turnOff");
}

void MyLightAdaptor::turnOn()
{
    // handle method call local.MyLight.turnOn
    QMetaObject::invokeMethod(parent(), "turnOn");
}

