/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a mylight_adaptor.h: ..\ex4\mylight.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MYLIGHT_ADAPTOR_H
#define MYLIGHT_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.MyLight
 */
class MyLightAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.MyLight")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.MyLight\">\n"
"    <property access=\"readwrite\" type=\"b\" name=\"isOn\"/>\n"
"    <signal name=\"lightChanged\"/>\n"
"    <method name=\"turnOn\"/>\n"
"    <method name=\"turnOff\"/>\n"
"  </interface>\n"
        "")
public:
    MyLightAdaptor(QObject *parent);
    virtual ~MyLightAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool isOn READ isOn WRITE setIsOn)
    bool isOn() const;
    void setIsOn(bool value);

public Q_SLOTS: // METHODS
    void turnOff();
    void turnOn();
Q_SIGNALS: // SIGNALS
    void lightChanged();
};

#endif
